version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, javascript]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, ci]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]
    labels: [dependencies, docker]
